#!groovy

// Generated by IBM TransformationAdvisor
// Wed Apr 03 04:20:35 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}